import java.util.Arrays;

public class HelloWorld{

    public static void main(String []args){

        System.out.println("NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXKKXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXKKKKK000000000000000000000KKKKXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXK000OOOOOOOkkkOOOOOOOOOOOOOOOOOO000000KKXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXK0000OkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOO0000KKKXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXKKK00OkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOO00000KKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK000OOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkkkkkkkkkOOOOO000O000KKXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXK0OkxkkkkxxxxkxxxxkkkOOOOOkkkkkkkkkkkkkkxxkxxkkkkkkkkkkkkkOOOOOOO0000KKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OkxxxxxkkxxxxxxxxkkkOOOOOOOOOOOkkkkkkkkkkxkkkkkkkkkkkkkkkkkkkOOOOOOOOOO00KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OkkxxxxxxxkkkxkkkkkkkkOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOO0KXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OkxxxxkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkOkkkkkkkkkkOOOOOOOOOOOOO000KXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKOxdddxxkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkOOOOOOOO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKOkdoddxkkkkkkkkkkkkkOOkOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkxxxkkkkkkkOOOOkkkkO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXK0OxddddxkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOkkkkkkkkkkkxkkxxxxxxkkkxxkkOOkkkkkk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKOxddoddxkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOO000OOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkxxxxxxxxxxxkkkOkkkxxxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0kxoooodxkkkkkxxkkkkkkkkOOOOOOOOOOOOOOOOOO000OOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkxxxxxxxxxxddxxxkkkkkkxxxkO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kddoodxxkkkkxxxxxkkkkkkkkkkkkOOOkOOOOOOOOO000OOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxdddxxxdddxxxkkkOkkxxdxkOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkdooddxxkkkkxxxxxxkkkkkkkkkkkkOOOOOOOOOOOOOOO0000000OOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxxddddddddddxxxxkkOkkxddxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0OxddddxxkxxkxxxxxxxxxxkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxxxxxxxxddddddddddddddxxkkkkkxddxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0OxddddxxkxxxxxxxxxxxxxkkkkkkkkkkkOOOOOOOOO0000OOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxxxxxxddddddddddddddxxkkkkkxdddxk0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKOkxdddxxxkxxxxxxxxxxxxxxxxxkkkkkkkOOOOOOOOOOO000OO_|-" +
                ",OOOOO00OOOOO00OOOOOOOOOOOOOOOOkkkkkkkkkxxxxxxxxdddddddddddddxxxxxkkxxdddxkOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0kxddddxxxxxdddddxxxxxxxxkkkkkkkOOOOOOOOOOOOOOOOOOO0000OOO0OOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxxdddddddddddddddxxxxkxxxxxxxkOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0kxxxddxxxxxxdddxdddxxxxxxxkkkOOOOOOOOOO00OOOOOOO00OOO00OOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxdddddoodddddddddxxxxxxxxxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kkxxddxxxxxxxxxxxddxxxxxxxxkkOOOOOOOOOOO00OOOO00000000000OOOOOO000OOOOOOOOOOOOOkkOOOOkkkkxxxxxxdddoooddddddddddxxxxxxxdxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkkxdddxxxxxxxxxxxxxxxxxxkkkkkOOOOOOOOOOO0OOOO000000000000000000000OO00OOOOOOOOOOOOOOOOkkkkkkxxxdddddddddddddddddxxxxxxxxxxdxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0OkxdddxxxxxxxxxxxxxkxxxkkkkkkOOOOOOO000000000000OO000000000000OOOOOOOOOOOOOOOOOOkOOOOkkkkkkkkxxxxxxxddddddddddddxxxkxxxxxxxdxxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0kxdddxxxxxxxxxxxxxkkkkkkkOOOOkkOOOOO000000OOOOOOOOOOOOOOO00000000OOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxxxxxdddddddoodddxxxkkxxxxxxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNXX0OkxxxxxxxxxxxxxxxxxkkkkkkkOOOOOkOOOOO000OOOOOOOOOOOOOOOOOO000000000OOOOOOOOOOOOOOOOkkkkxxkkkkkkxxxxkkxxddddoolodddxxxkxxxxxxxxxkOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNXXK0kkxxxxxkkxxxxxxxxxxkkkkkkkkOOOOOOOOOOOOOOOOOOOO000OOOOOOOOO00O0000OOOOOOOOOOOOOOOOOOOkkxxxkkkkxxxxxkkxxddddooooddddxxkxxxxxxxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNXX0OkkkxxxkkkkkxxxxxxxkkkkkkkkkOOOOkkOOOOOOOOOOOOOOOOOOOkkkkkOOOO00OOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxxdddooodddddddxxxxxxxxxxxxxkO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNXK0kkkkkkkkkkkxxxxxxxkkkkkkkkOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxdddddoodddddxxxxxxxxxxkkkkkkO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNXXKOOkkkkkkkkkkkkkxxxxxkkkkOOOkkOkkkkOkkOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxddddddddoodddddxxxxxxxxxkkkkkOO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNXKOOkkkkkkkkkkkkkxxxxxxkOOkOOOkkkkkkkkOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkxxxxxxxddddddddddddddxxxkxxxxxkkkkOOOO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNX0OkkkkkkkkkkkxxxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkxxxxxxxddddddddddddddxxxxxxxxkkOOOOOOO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNXK0OkkOOOkkkkkkkxkxxxxxkkkkkkkkkkkkkkkkOkkOOO00OOOOOOOOOOOOOOOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOkkkkkxxkkxxxxddddddddddddddxxxxxxxxkkOOOOOO00XXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNXKOOOOkkOkkkOkkkkxxxxxxxxkkkkkkkkkkkkkkkOOOO00OOOOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOkkkkkOOOOOOOkkkkkkxkkxxdddxdddddddddddddxxxxxxxxkkOOOOO000KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNXKOOkkkOOkOOOOkkkxxxkxxxxkkkkkkkkkkkkkkOO0000000OOOOOOOOOOOOOOOOOOOOkkOOkkkOOOOOOOOkkOOOOOOkkkkkkxxxkxxdddddddddxxxddddddxxxxxxxkkOOkOOOOO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNXX0OOkkkkkkOOOkkkkkxxxxxxkkkkkkkkkkkkkOOOO0000000OOOOOOOOO0000000OOOOOOOOOkOOOOOOOOOOOOOOOOOOkkOkkkkxxxxxdddddddddxxxxxdddddxxxxxxkOOkkOOOOOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNXK0OkkkkkkkkkkkkkkkxxxxxxkkkkkkkkkOOOOOOOOOOOOOOOOOOOOO0000000000OOOOOOOOOOOOOO0OOOOOOOOOOOkkkkkkkkxxxxxxddddddddddxxxxddxdddxxxxkkkkkkkkkkOOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNXX0OkkkOkkkkkkkkkxxkxxxxxkkkkkkkkkOOOOOOOOOOOOOOOOOO000000000OO00OOOOOO0OOOOOOkOOOOkkkkkkkkkkkkkkkkxxxxxxxdddddddddddddxxxxxddddxxkkkkkkkkkkOO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNXKOkkkOOOkkkxkkkxxxkxxxxxkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOO0OOOOOO00OOOOOOOOOOOOOkkkkOkkkkkkkkxxxxxxxxxxxxddddddddddddooddddxxxxxdddxxxkkkkkkkkOOOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNXK0kkkkkOOkkkxxxxxxxxkkkkkxkkkkkkxxxxddddooooooooooooooooodddxxkkOOOkkkkOOOOOkkkxxkkkkkxxxxxdddooooloolllccllllcllllllllloodddddddxxxxxxkkkkkkkO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNXKOkkkkkkOkkxxxxxxxxxxxxxxddoooooodddooooooooooolllccc::cccccclllloooddxkOOkkkxxxxxkkxxxdddolc:::::::::cccccllooooddodddddddddddddddooddxxxxxkkkOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNXX0Oxxxxkkkkkxxddool:,:dxdollodxkkO0OOOkkkkkkkxxdooooollloooddddxxdolllc;;;::::::::clcc:::;;;;;;::ccccllllllloodxxxxxxxxxdxxxxxkkkkkkkxo:;;,':dkkOKXNNXXXXNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNXX0kddxxxkkxdl:;;;;,..,cl::ldxkkkkkOOOkkkxkkkxxddooooooooooooooddxxxxxxd:.........''''''...;cccccccccccclloooddddxxddddddddddxxxxxkkO00Oo;,,,:dxxkO00kxxxk0KNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNXX0kddddddolc;,,;:::cccc::cooddooodxkkkkkkkkxxxdddoollcllodddooooodddxxxdc:ccoooolllc::cc;;llccccc::::cclloodddddddddddddddddddxxddxdoooollooc;,;:loooooodxO0XNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNXXKKXXXXK0xdooc;,,;;::llooooooolloodxdodxkkkkkxxxdxdddoollllllllooooollooodddddc:ldxkxxxddollll::lc:::::;:ccccc:;;;:;::ccllolooddddoddxddxdlloddoddoc;;clooodoooooxKNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNX0OkxxkkO000Oxoc;'';:cloddddxxxxxxxxxkkxxxkkkxxddddolc::;,;:::cllllllllllllooddoo:,cdkkkkkxdollll;;cc:;;;;::cc;,:;..,;,,;:::cclcclodddddxxxkkxxxkkxxkkxoooooooolll::oOXNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNXOxxxxxxxxxxxxdl::clodddxxxxxxxxxkkkkkkkkxxkxdoooolll:,;c;.'::;:lollllllcccllolc::;:oxOOOkkxxdoooo:,:lc:::;;;:c:,,,'',;,;clcc::cccclooodxxkkkOkdxkOxkkkkxddddolclll::lkXNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNKkdoddxxxkkkxxxdodxxxxddxxxxxxxxxkkkkkkkxxxdollllloddo:::;,,;;:lddollllooloool:,;:;ldkkOOOkkxdoodo,.;llcc:;;;:cc:;;:::::clllllolllllloodxxkkOkxdxOkkkkkOkdddolccllc::lkXNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNX0xollddxxxkkkkkkkkkxxxdddxxxxxxxxxxxxkkxxdddoooddxxxxxollcccclldddoolllodxxddlc:ododkkkkkkkkxxoooo;.,lllcc:::::cclloooddooooooooooooooodxxkOkxxxkOkkkkkkkxdoolllllc::lkXNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNX0kocldxxdxxkkkOOkkkkxddddxxxxxxxxxxxxxxxxdddddxxkkkkkkxxxddddddddddooooodddddddxkxxkOkkkkkOkkxdoool::llccc::::::ccllooooolllloooooddddodxkkOkxxkOOkkkkkkxooooolllol::oOXNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNX0ko:ldxxxxxkkkkkkkkkxdddxxxxxxxxxxxdxxxxxxdxxxxxxxkxxxxxddddoooooooooooloodddxkkxxkOOOkkkkkkkxdooooollolcc:::::::cclllllllllllooooooddodxkOOOxxOOkkkkOkxolloooolllc:cd0NNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNX0ko:ldxxdxkOOOkkkkkkxddxxxxxxxxxxxddxxxxxxxxxxxxxxxxxxxddddddooooooooooodddddxxxdxkOOOOOkkkkxxddooooolooolccccccccccclllllllllllooodddddxkOOkxkOkkkkkkxooooooooollcclxKNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNXKkdcldxxxkkkkkxxkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddxxxddxxxxdxkkkkOOkkkkkkxxddoooolloooolllllllllllllllllloooddddddddxkOOkxkkkkkkOxlcloooooddollld0NNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNX0koldxxkkkkkkkkkkkkxxxxxxxxxxxxxkkkkkkxxxxxkkkkxxxxkkkkkxxxxxxxxxxkkkkkxxxxxxxxxkkkkkkkkkkkkxxdddooollloooooooooooooooooooodddddxxxxxxxxxxxxxxkkkkkkdc:cllooooddllokXNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNKOxoodxkkkkkkkxdloxxxxxxxxxxxxxkkkkkkkkxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxkkkkxxxxxxxxddddoooolllooooooodddddddddddddddxxxxxxddddddxxxkkkkkkxoclllllloddooxKNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNKOxdxkOkkkxxdoc:cdxdddxxxxxxxxkkkkkkkkkkkkxxxxxkkkkkkkkOOOOOOOOOOOkkkkxdxxxxxxxxxkkkkxxxxxxxxdooooooolloooooooooooooooooooodddddddxxddddddxxxkkkkkkkxollccccoddddOXNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNXKOxkOOxxxxxdolloxxdddddxxxxxxkkkkkkkkkOOkkkkkkOOOOOOOO00OOO0OOOOkkkkxxxxxxxxxxxxxxkkkkkkkxxxddoooooooooooooooddooooooooloodddxxddxxdddddxxxxxkkkkkkxdlc:::codddkKNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNX0kkOkxdddddoodxkxdddddxxxxxxkkkkkOOOOOOOOOOkOOOOOOOO000OOOOOOOkkkkkkkxxxxxxxxxxxxxkkkOOOkkxxxddddoooooooooooooodddddoooooddddddddddddxxxxxxkkkkkkxxdl;,;:coddxOXNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNXKkkkkdollloodxkkxdddddxxxxxxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkxxxxxxxxxddxxxxkkOOOOkkkxxdddddoooooooooooooodddddooooddddddddddxxxxxxxxkkkkkkxddc;,;cloddxKNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNXOkkkxoccclodkkOkxddddxxxxxxkkkkkOOOOOOOOOOOOOOOOOkOOOOOOkkkkOkkOkkxxxxxxxxxxxxxxkkkkkkkkkkxxdooddoollllloooooddoodddooddddddddddddxxxxxxxxkkkkkxddoc:cloodddkKNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNX0kkkxol:::ldkOOOkdddddxxxxxkkkkkOOOOOkOOOOO0OOOOOOOOOOOOOOkkOkkkkkkxxxxxxdxxkkkkxxxxxxkkkkxddoddddoollllllooooooooddddddddddddddddxxxxxxxxkkkkxdddoloodddoodOXNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNKOkkkxol::coxkOOkxdddddxxxxkkkkkkkOOOOOOOOOOOOO0000OOOOOkkkkkkxxxxxxxxxxxxxxkkxxxxxxxxkkkkxdodddddoooollllllllloooodddddooodddddddxxxxxxxkkkkkxdddloddxxdodxKNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNX0kkkkxddooooxkOkxdodddxxxxkkkkkkkkkkkOOOOOOO000000OOOOkxddxxddooddxxxxxxxxxxxkkkkkkkkkkkkxdooodddddddollllcccccloooooooooddddodddxxxxxxkkkkkxddddodddxxxxxOXNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNXKOkxkkkkkkdodkOOkxdoddxxxxxkkkkxkkkkkkkOOOO000000OOOOkkddoddddddxxxkkkxxxxxxxkkkkkkkkkkkkxddodxxxxddddolllccc:ccllloooooddddoooddxxxxdxkkkkkdoodddddddxxxOKNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNX0kkkkkOOkxddkkkkxdoddxxddxxkkxxxkkkkkkOOOOOOOO0OOOOkkxxdddxxxxxxkkkkkkxxxxxxxkkkkkkkkkxxdddddxddoooooolllllccc:ccllllloooodddddxxxxddxkkkkxdoooddddddddx0XNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNXKOkkOOOOOOkkkkkkkxddxxxddxxxxxxxkkkkkkkOOOOOOOOOOkkkxxxxxkkkkkxxxxxxdollooddxxxxxxxxxxddoooollccc:cllolllllllcccccllllloooooodxxxxxddxkkkkxdddddddddddxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNX0OkOOOOOOOOkkkkkxddddxxxxxkkkxxkkxxkkkkOOOOOOOOkkxxxxxkkkkkkkxxddolccclllooddddxxxdddoodollcccccclloolllllllllcccclllllooooodxxxxxddxkkkkdddddddddddxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNX0OOOOOOOOOkkkkkkxdddddxxxxkkxxxkxxxxkkkOOOOOkkxddxkkOOkkkkkkkkxxdddddxddxxddddddddooooooollllllooollllllllllllcccclllllloooodxxxddxxxkkxdoodddddxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNX0OOOOOOOOOOOOOOkdddddxxxxkkxxxkkxxxxkkkOOkkxdddxkOOkkkkkkkkkkkkkxxxxxxxxkxxddddoooooooooooooooooollllllllllllllcccllllllooodxxdxxxxxkkOOOkkxkkO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNXKOOOOOOOOOOkkkkxddddddxxxxxxxkkkxxxxxkkkxdddxkkkkkkkkkkkkkkkkkkkxkkkkkkkkkxxddddoodddoooooooooooollllllllllllllccclolcloodxxddxxxxkkOKNNNXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNXK0OOOkkkkO00kdddddddxxxxkxxkkkxxxkkkkkxdxkOkkkkkxxxxkkkkkkkkkkkkxkkOOOOkkxxxxxddddddddooooooooooolllllllllllllccloolloddxxddxxxxxkOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNXXKKK0KXXNXkdoddddxxxxxkkkkkkkxkkkkkxdxkOOkkkkkkxxxkkkkkkkkkkkkxkOOOOOOkkkxxxxddxxxxddddoooooooooooooooollllllclooollddxdddxxxxxkOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xdddddxxxxxxxxxkkkxxkkOkxxkOkkkkkkkkkkkkkkkkkOOOOOkkOOOOOOkkkkkxxxxxxkxxxxxdddooooooooddddooollooollloollddxdddxxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOxddddxxxxxxxxxxkkxxkOOkxxOOOOOOOOkkkkkkkkkOOOOOOOOOOOOOkkkxkkkkxkkkkkkxxxxdddooooooddddddoooooooolllooloddxdddxxxxxk0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xdddxxddxxxxxkkkkkkkOOkxkOOOkOOOOkkkkkkkkkOOOOOOOOOOOOkkkkkkkkkkkkkkkkkxxdddoooooooodddoolllloooooloddloddddodxxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xddddxdodxxxxkxkkkkkkOkxkOOOkOOOkkkkkkkkkkkkOOOOOOOOOkkkkkkkkkkkkkkkkkxxddooollllllllc;;;:ccloooooodddlodddddxxxxxkOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkddddxddddxxxkxxkkkkkOOkxkOOOOOkkkxxddddddxxxxkkkkkkkkkxxxxxxxdddxxxddooollccccccc:;....';ccloooooddxolodddddxxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xdddxxdddxxxkkkkkkkkOOkxkOOOOOkkkxxdl;,,;cooooooooooooooooooollllllcc:cc:cc:;:lc:,...,;:clllooddddxdolodxddxxxdxkOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kddddxddxxxxxxkkkkkkkOOkxkOOOOkkkkkxxoc;;:loooooollooooooollccc:::c::cc::cc;,;::,,,;:ccllloodddddxxdooddxddxxxxxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKkdddddddxxxxxxxxkkkkkkOOkkOOOOkkkkkkkkxxdoollodddolodooodddooll:;cllllc::::;;:::::cclllllooooddddxdooodxxdxxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXOxdxxxdddxxxxxxxxkkkkkOOOkkOOOOOkkOkkkkxxxxddddooollllooddooooollooooollllllcccclllloooooooooodddddoooddddxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0xdxxxxdxxxxxxxxxxkkkkkOOkkkOOOOOkOOkkkkkxxxxxxddddddddddddddddddddddddoooolllllooooooooooooooodddoooddddxxxxxk0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kdxxxxxxdddxxxxxxxkkkkkOkkkkOOOOkkkkkkkkkxxxxxxxxxkkkxxxxxddxxxxxdddddddoollloodddddooooooooooddooooddddxxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKkxxxkkxxxddddxxxxxxkkxxkkkkkkkkOOOkkkkkkkkkkkxxxxxkkkxxxdddddxxxddddddooooooooodddddooooooooooddoooddddxxxxddkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOxxxkkkxxxdddxxxxxxkkkxxkkxxkkkOOOkkkkkkkkkkkkkkkkkkxxxddddddddddddddoooooooooddddddoooooooooddooodoodxxdddddkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxxxxkkxxxxxdxxxxxxxkkkxxkxxxkkOOOOkkkkkkkkkkxkkkkkkxxxxxxxddddddddddddddooloooooddooooooooooddoodoodxxdoooddkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0xxxxkkxxxxxxxxxxxxxxkkxxxxxxkkkkOOOkkkkkkkkkkkkxxxxxddddddxxxddddoodddoooooooooooooooooddooddddooodxxolooddxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxxxxkkxxxxxxxxxxxxxxkkxxxxxkkkkkkkkkkkkkkkkkkkkkkxxddddddddddooooooooooooooooooooooooooooddddddoddxdooooddxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOxxxxxkkxxxxxxxxxxxxxxxxxxxxxxkkkkkkOOkkkkkkkkkkkkkkxxxddddddddoooooooooooooooooooooooodooddxddddddddoooooddxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOdcldxxxxxkxxxxxxkxxxxxxxxkxxxxxxkkkkkkOOOOOkkkkkkkkkkkxxxxxddddooooooooooolooooooooooooooodddxxddddxdolloooodk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOxc,:dddddxkkxxxkkkkxxxxxxxxxxxxxxkkkkkkkOOOkkkkkkkkkkkkkxxxxdddddddooooooollooooooodddoooooddxxddddxdollloooodkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKOkd:;oddddxkkkxxkkkkxxxxxxxxxkkxxxxkkkkkkkOOkkOOOkkkkkkkkxxxxddddddddooooooooooooooddddoooodddxxdddddollllooodxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX000OkdclodddxxkkkxxxkkkkxxxxxxxxkkkxxkkkkkkkkkkkOOkkkkkkkkkxxxxxxxxxddddddoooooooooodddddooodddxxxddddooolllloodxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0OK0kkxooxxxxxxxkkxxxkkkkxxxxxxxxkkkxxkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxddxxdddooooooooodddddoooodxxxddddoodolllooodxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0000K0OOkddxxxxxxxxxxxxxxkkkxxxxxxxxkxxxxkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxdddooooooddddooddddxxdddooodollllooodx0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK00K00K0O0OxdxxxxxxxxxxxxxkxxxxxxxxxxxxxxxxkkkkkkkkkkOOkkkkkkkkkkxxxxxxxxxxxxxxdoollooooddoodddxxddooloooollooooddx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK0KO0K00K0O0OxdxxxxxxxxkxxxkxxxxxxxxddxxxxxxxkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxddoooooooooodddxxddolllloolllooooddddOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXX0O0K00K00K00K0xdxxxxddxxxxkkxxxxkkxxxdddxxxxxxxkkkkkkkkkkkkkkkkkkkkxxxxkxxxxxxxddoooooooooooddxxddoolllllllllooooodl:cd0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0K00KK0KK00K00K0xddxxxxxxxxxxxxxxxxxxxxddddddxxxxkkkkkkkkkOOOkkkkkkxxxxxxxxxddxxddoooooooooodddddddoollllllllllllool:,,:okKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXK00K00KK0KK00K00K0xodxxxxxxxxxxxxxxxxxxxxdddddddxxxkkkkkkkkkkkkkxxxxxxxxdddxxddddooooollooooooddoodoooolllllllllllll:'.',:lx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKK00K00KK0KK00K00KKkdooddxxxxddxxxxxxxxxxdddddodddxxkkkkkkkkxxxxxxxddddddddddddooollllllooooooooooooooollllllllllllc;....,:lx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNNXK00KK00K00KK0KK00K00KKkdolcoxxxxxxxxxxxxddddddddddddddxxxkkkkxxxxxxxxddddddddoooollllllloooooooooooooolllllllllllllcc:'...'',cox0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNNNNXK0K00KK00KK0KK0KK00K00KKOxdc:codxxxxxxxxxxdddddddddddddddxxxxxxxxxxddddddddooooooollllllllllllooooooooollllllllllllccc;.....,,;lxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNXNNXK00KK0KK00K00KK0KK00KK0KKOkko;;codxxddxxxdddddddddddddxxxxxxddddddddddoooooooollllllllllllllloooooooooollllllcclllccc:,. ...',;:oxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNNXXX0KK00XK0KK00K00KK00K00KK0KK0OOxc,,:loddddxxddddddddddddddxxxxxxddooooollllllllccccccclllooooooooooolllllllllllcclllccc:'   ..',;clokOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNNNNNNNNNNNNXXXK00KX00KK0KK00KK0KK0KK00KK0KK0O00o;',:codddxdddddddddddddddddxxxxxdxddollccccccllllllooooooooooolloolllllllllllllllllcc;.   ..',,:lodxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "NNNNNNNNNNNNXXXXXXXXKK0000KXK0KX00KK0KK00KK0KK00KK0KK00KK00Kkc,'';:lodddddddddddddddddddxxxxxxxxxxdoooooddxxxxdddddddddooollolllllllllllcclllllc:'.   ..',;::oddxOKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\n" +
                "XXNNXXXXXXXXXXXKK00OOO00KK0KXK0KX00XK0KK00XK0KK00KK0KK00XK00K0d:,'',:coddddddxddddddddddddxxxkxxkkkkxxxkkkkkkkkxxxxxdddooollllllllllllccccllllc:;.    ..',:llcoxdxO00KXXXNNNNNNNNXXXKKK0000KKKXXXNNNNNNN\n" +
                "XXXXXXKKKKKK00OOOOO000000KK0KXK0KX00XK0KX00XK0KXK0KK00KK0KX00KXOdc;'',;clooodddddddddddddxxxxkkkkkkkkOOOOOOOOkkkkkkxxddoollllllllllllllcccllllc:,.    ..,:clddooddxkOOOO00KXKK0OkxxdoolloodddxxkOO0KXXNN\n" +
                "XXKK000O000OOOO00K000O000KXK0KXK0KX00XK0KXK0KX00XK0KX00KK0KXK0KXKOdl;,',;:clodddddddxxxxxxxxxxkkkkkOOOOOOOOOOOkkkkkxxdoolllllccllllcclllccllllc;'.    ..;coooxkxdddxOOkkkkkkkkxxdolccccccclloodxxxxkOOO0\n" +
                "K000OOOOOOO0000000000O0KK0KXK0KXK0KX00XK0KXK0KX00XK0KXK0KXK0KXK0KX0kxo:,',,;cloooodddddxxxxxxxxkkkkOOOOOOOOOOkkkxxxxxdolllllcccllllccllllllllc:;.    ..,:loxxdkOOxxxkOOkkkkkkkkkkxddollccccllodxkkxdxkxd\n" +
                "0OOOOOOOOOOOOO000000OOOKXK0KXK0KXK0KX00XK0KXK0KXK0KXK0XK00XK0KXK0KXK0Okxl;,,,;:cloooodddddxxxxxxxxkkkkOOOOOOkkxxxxxdddoolllcccllllllllloollllc:,.    .':looxOkxk00OkdokOkkkkkOOkkkkkxdolccclloxxxkkdodxd\n" +
                "OOOOOOOOkOO0000000KK0O00KXK0KXK0KXK0KXK0XX00XX0KXK0KXK0KXK0KXK0KXK0KXKO00xl;'',;:clloodddddddddddxxkkkkkkOOkkkxxxxxddoolllccccllllllllloollllc;'.    .;lodxxkO0kO0Oo:;coxxxxxkkkkkkkkxdolllccldxkxxkdlod\n" +
                "OOOOOOOkkkOO0000KK00KK0O0XXK0XXK0KXK0KXK0KXK0XX00XX00XK0KXK0KXK0KXK0KXK0000xc;,,;;:ccloooooddddddddxxxxxkkkkkkxxxxddoollllcccllllllloooollllc:;'.   .':oxxxOOOOkdl;'',:coxkxxxkxkkkkkxxdolc::coxkxxxxdll\n" +
                "OOOOOOkkkkOO000000KKK00K00XXK0XXK0KXK0KXK0KXK0KXK0XXK0XXK0XXK0XXK0KXK0KXK00K0xc;;;;;::cccllodddddddddddddxxxxxxxddoolllllccccllllllooolllllc::,..   .;odkOkkOkd:.   .';:coxkkxdxkkxxkkxxdlcccllodxxdxxdl\n" +
                "OOOOkkkkkkkO00000K0O0KK0OO0XXK0XXK0KXK0KXK0KXK0KXK0KXK0KXK0KXK0KXK0KXK0KXX00KKOdc:;;;;::cclloloooodddddddddddddoolllllllccccclllooooooolllc::;,..  .;dkkkkkdl;..     ..';:odxxddxkxxxxxxxdollcclodxxdddd\n" +
                "OOOkkkkkkkkkkO0K000KK0O0Okk0XX00XXK0KXK0KXK0KXK0KXK0KXK0KXK0KXX0KXX00XXK0XXK0KXKkoc:::::ccccccccllooooooodddooollllcccccccllllloooolollccc::;,,'':odkOOxolc;'.        ...':odxxdodxxdodkxxxddolclldxxxdd\n" +
                "OOOOOOkOkkkkOOOO00000OO00kxk0XX00XXK0KXK0KXX0KXX00XX00XX00XX00XXK0XXK0KXK0KXX00XX0kdolccclllcccccccclllooooooolllccccccclllllooooooolc::c:;;,,;lxOOkxddol;'.'.         ...'cdxxxxdodddooxkxxxdoooodxxkxd\n" +
                "OOkk00kkkkOkkkOO00OkO00OOOkOO0XX00XXK0KXK0KXK0KXX00XX00XX00XXK0XXK0KXK0KXX0KXXK0KXKOkkxollloolllccc:::cclloooollllccccclllloooooooolc::::;;;:lxOkxdddol:;:;,,,.          ..,cdkxxxdddddloxkxxxddoodxxxxx\n" +
                "kkkkO00kkkkkOOOkxkOOOO000OO00O0XX00KXK0KXK0KXX00XX00XX00XXK0XXK0KXK0KXK0KXX00XNK00K0kxkkxxddddoolllcc:::::ccllllllllllooooooooollllc::;;;;:lxkkxxxddoooc;:cc;:;..  .      ..;ldkkxxxxdddlodxxdxxxxxxxxxx\n" +
                "xxkkkOK0kkkkkkkkkkOOOOOO000O0KO0KX0OKX00KXK0KXX00XX00XX00XXK0KXK0KXK0KXX0KXXK0KX0xolccldkO0000Okxdollccc::::cccllooooodoooollolllc::;;;,:oxkkxxxxxxddlodc;:llcc;......  .. ..'cdkkxxkxdoolldxxdxxxxxkkkx\n" +
                "kxxOkkO0OkkxxkkxxkO0OOO00OO0KXKO0KKOOKX0OKXK0KXK00XX00XX00KXK0KXK0KXX00XXK0XXKOdl::::::coxOO0000OOkxxxxolcccclloooooooooollccclcc:;;;,;lxkkxxxxxxxddddlooc:collc;..........  ..:dkkkkkkdooolodxddxkxxxxk\n" +
                "kxxkOkkO0Okkkxkkkxk0K0O0KKOOO0XKOOKKOOKX0OKXK00XK00XX00XXK0KXK0KXK0KXX00XXKOkxl::;;::::coxO00KKKK00OOOOOkxdollllloolllcccc:::::::;;,,,lkkkxxxxxxxddodxolooc:ldllc;,,............,lxkkkkkoloolldxddxkxxxx\n" +
                "kkxxkOkkO0kxkkkkkkkkO00OOKK0kk0K0OOKKOOKK0OKXKO0XK00XX00XXK0KXK0KXX0KXX000ko:;;;:::::::coxk0KXXXKK0OkkkkOOOOxolccllcccc::::;;:;;;,,,,,oOkkxxxkxxxdddoxxlcooccddlll:::;,,,........':oxkkkkdlodoloxxdxkkxx\n" +
                "kkkxdkOkkOOkxkkkkOkkkkO0OO0K00O0K0OOKKOOKK0OKX0O0XK00XX00KXK0KXK0KXX00K0xl:;:;,;::;;::clodk0KKXXKKKK0kxxkOO0OOxollcccc::;;;;;;;;;,,,,,lkkxxxxxxxddxxdoxdlcolclxdooolloc:c:,,,'.....':dxkkxdlldoloxxxxkkk\n" +
                "kkkkddkOkkOOkkkkOkkkkkkO0Ok0KX0O0K0OOKKOOKK0OKX0OKXKO0XX00KXK0KXK0KXKkdc:c:,;:,,;;,,:c:lodxO0KKKKKK00kdddxOOOOkkxoccc::;;,,,,,;;,,,''':xkxxxxxxxdddxxooxdlcllcoxdooolodolooccc;,,'...,cdxkxxolooloxOkxxk\n" +
                "xkxkkddkOkkOOkkkkOkkxkkxkOkkOKX0O0X0O0KKOOKKOOKX0O0XKO0XX00KXK0KXKOkdoolccc;,:;',:,';c::ldddxk0000OkkxdododkkOOOOkdlc:;;,,,,,,,,,''''';dkxxxxxxxxdddxxooxoccolldxdodolddoodoldoclc;,,.',cdxkxolododkOkxx\n" +
                "kkxxkkdxOOkkOOkkkkkkxxxxdxkkkOKK0O0K0O0KKOOKKOOKX0O0XKO0XX00KX0kkddxdlodollc;;:,;c:,:lc:codddodxxxxxxxxxxddxkkOOOOOxoc:;,,,,'''''''''';dkkxxxxxxxxdddxdoddlcloloxxdodooddodxodxooxoll:;,,;coxxocoxxxOOkx\n" +
                "kkkxxkkdxOOkkOOkkkkkkxxxooxkOOO0K0O0K0O0KKOOKKOOKK0O0XKO0K0kxdooolloxdlodooolcc;;clccddlldxdddddxkkxxxxxkxxxxxkkxkkkkxdl:,'''''''''''':xkxxxxxxddddddxkdoddlcooldkxoddooxdoxdoxxdxxdddolc::ccodooxOkkkOO\n" +
                "kkkkxxkkdxOOkk0Okkkxxxddollx0K0O0K0O0K0O0K0O0KKOOKKOO00kddoc:c::odlldxdodxdoddol:cooldkxodkxdxkkxkOkkkkkkkkkkkkxkkxxkxkkxoc;''''''''''ckkkxxxxxddxdxddxxoldocldooxkxdddodxddxddkddxxdxxdxdodoloxxxk0OkkO\n" +
                "kkkkkxxOkdxOOkk0OkkkxxdollcokKK0O0K0O0K0O00OkkOxdxdddoodl:cc:clcldxddkOxdkOxdkxdoodxooxkxdkOxxO0kk000OO0OkO0OOOOkkOkkOkkkOkxl;''''''',lkkxxxxdxxdxdxxodxdlodlcodookkxdddodddxxdxxdxkdxkdxkxxkxdxkkxO00kk\n" +
                "0kkkkxxkOkdkOOkk0kkkxxdollllxOKKOOK0OkOxoddlcllccooloooddlloolododOOkk00kk00kkOOxxxxdookkdxOOxk00kOKXKO0K0OKX0OKKO0K0O00O00OOxc''.''';dkkxxxxddxddxdkxodxoloolldxodkkxddddddxkxdkxdkxxkkxkkxxOkxxOOkO0Ok\n" +
                "KOOOkkxxxOkdk0OkkOkxxdoolloddx00kO00kxkxlldollddoododdodxdodxddkOkOK0OOKKOO00kk0OkkOxoodkxdxOOxO0Ok0KK0OKX00XKO0XKOKKO0K0O0KOOkc''..'lkkkxxxxxdxxdxdxkdoxxllooloxxdxOkdddddxdxxdxkxxkxxkxkOkxkOkxk0OkO0O\n" +
                "KOO0kkkxdkOxxO0kkOOxxxdodooxddO0Ok0KOkO0kodkxodkxoxdoxddkxddOkxOK0OKX0O0K0kOK0kO0OkOOxddxkddkOkk00kO0KKO0XKOKX0OKX0OKKO0KOOK0OOx:''.;dkkxxxdxkdxxdxxdkxodxdcldoldkxxOOxdddddddkxxkxxkkxOkxkOkxkOkxOKOkOO");

    }
}